// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/11/2025, 3:13:49 PM
const configMerger = require("/Users/dinaab/Desktop/school/new-port-web/port2/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/dinaab/Desktop/school/new-port-web/port2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dinaab/Desktop/school/new-port-web/port2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dinaab/Desktop/school/new-port-web/port2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dinaab/Desktop/school/new-port-web/port2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dinaab/Desktop/school/new-port-web/port2/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dinaab/Desktop/school/new-port-web/port2/plugins/**/*.{js,ts,mjs}","/Users/dinaab/Desktop/school/new-port-web/port2/composables/**/*.{js,ts,mjs}","/Users/dinaab/Desktop/school/new-port-web/port2/utils/**/*.{js,ts,mjs}","/Users/dinaab/Desktop/school/new-port-web/port2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/dinaab/Desktop/school/new-port-web/port2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/dinaab/Desktop/school/new-port-web/port2/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["23"] = "/Users/dinaab/Desktop/school/new-port-web/port2/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})()
